# Generated by Django 3.0.2 on 2020-05-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=1000)),
                ('user_loc', models.CharField(max_length=1000)),
                ('user_password', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='RCForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Road_name', models.CharField(max_length=1000)),
                ('RC_reason', models.TextField()),
                ('RC_Cost', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcform', to='Rcutting.User')),
            ],
        ),
    ]
