# Generated by Django 3.0.2 on 2020-05-25 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rcutting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rcform',
            name='user',
        ),
    ]
