# Generated by Django 3.0.2 on 2020-05-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rcutting', '0002_remove_rcform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcform',
            name='RD_ctgry',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AddField(
            model_name='rcform',
            name='RD_lclty',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AddField(
            model_name='rcform',
            name='RD_len',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='rcform',
            name='RD_loc',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AddField(
            model_name='rcform',
            name='RD_type',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AddField(
            model_name='rcform',
            name='RD_ulbn',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AddField(
            model_name='rcform',
            name='RD_wn',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AddField(
            model_name='rcform',
            name='applcntaddres',
            field=models.TextField(default='NULL'),
        ),
        migrations.AddField(
            model_name='rcform',
            name='applcntdist',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AddField(
            model_name='rcform',
            name='applcntpin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rcform',
            name='applicant_mobno',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rcform',
            name='applicnt_email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='rcform',
            name='applicnt_fname',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AddField(
            model_name='rcform',
            name='authtokn',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='rcform',
            name='RC_Cost',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='rcform',
            name='RC_reason',
            field=models.TextField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='rcform',
            name='Road_name',
            field=models.CharField(default='NULL', max_length=1000),
        ),
    ]
