# Generated by Django 3.0.2 on 2020-05-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rcutting', '0003_auto_20200525_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rcform',
            name='applicnt_email',
            field=models.EmailField(default='none', max_length=254),
        ),
    ]
