# Generated by Django 3.0.2 on 2020-05-25 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rcutting', '0006_auto_20200525_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rcform',
            old_name='Road_name',
            new_name='applcnt_name',
        ),
    ]
