# Generated by Django 3.0.2 on 2020-05-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rcutting', '0007_auto_20200525_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='rcform',
            name='usr_consmcode',
            field=models.CharField(default='RC/06-02-2020/000002', max_length=1000),
        ),
    ]
